# Generated by Django 4.2 on 2023-06-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_ad_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='image',
            new_name='ad_image',
        ),
    ]
