# Generated by Django 4.2 on 2023-06-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_advertisementmodel_delete_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('ads_image', models.ImageField(blank=True, null=True, upload_to='ads')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AdvertisementModel',
        ),
    ]
