# Generated by Django 4.2 on 2023-06-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_adsmodel_delete_advertisementmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsmodel',
            options={'verbose_name': 'Ads', 'verbose_name_plural': 'Ads'},
        ),
    ]
