# Generated by Django 4.2 on 2023-06-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_adsmodel_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdsModel',
            new_name='AdvertisementModel',
        ),
    ]
