# Generated by Django 4.2 on 2023-06-13 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0015_adscomment_created_at_adscomment_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicked_ads', to='pages.ads')),
                ('clicked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicked_ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
