# Generated by Django 4.2 on 2023-06-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_adsclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('women_count', models.PositiveBigIntegerField(default=0)),
                ('man_count', models.PositiveBigIntegerField(default=0)),
                ('total_count', models.PositiveBigIntegerField(default=0)),
                ('age_range', models.CharField(blank=True, max_length=100, null=True)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pages.ads')),
            ],
        ),
        migrations.DeleteModel(
            name='AdsClick',
        ),
    ]
