# Generated by Django 4.2 on 2023-06-14 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_adsreport_delete_adsclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisement', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
