# Generated by Django 4.2 on 2023-06-15 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0019_alter_ads_ads_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateField(auto_now_add=True)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_click', to='pages.ads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_click', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
