# Generated by Django 4.2 on 2023-06-15 04:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_adsclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
