# Generated by Django 4.2 on 2023-08-14 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_conference_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conf_image',
            field=models.FileField(blank=True, default='default-photo.png', upload_to='conference', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.FileField(blank=True, default='default-photo.png', upload_to='news', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
