# Generated by Django 4.2 on 2023-05-01 10:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='beauty_center_default.png', upload_to='beauty_center/image_upload', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png'])])),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeautyCenterStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beauty_center_staff', to='beauty_center.beautycenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beauty_center_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
