# Generated by Django 4.2 on 2023-05-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautycenter',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
