# Generated by Django 4.2 on 2023-05-16 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_center', '0003_alter_beautycenter_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautycenter',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
