# Generated by Django 4.2 on 2023-05-01 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_hospital_city_alter_hospital_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, default='default-hospital.jpg', upload_to='hospitals/image_upload', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png'])]),
        ),
    ]
