# Generated by Django 4.2 on 2023-05-01 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_hospital_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='default-hospital.jpg', upload_to='hospitals/image_upload', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png'])])),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='city',
            new_name='address',
        ),
    ]
