# Generated by Django 4.2 on 2023-05-01 10:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0004_beautycenter_rename_city_hospital_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beautycenter',
            old_name='city',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='beautycenter',
            name='image',
            field=models.ImageField(blank=True, default='beauty_center_default.png', upload_to='beauty_center/image_upload', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png'])]),
        ),
        migrations.CreateModel(
            name='BeautyCenterStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beauty_center_staff', to='hospital.beautycenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beauty_center_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
