# Generated by Django 4.2 on 2023-05-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_rename_city_beautycenter_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beautycenterstaff',
            name='beauty_center',
        ),
        migrations.RemoveField(
            model_name='beautycenterstaff',
            name='user',
        ),
        migrations.DeleteModel(
            name='BeautyCenter',
        ),
        migrations.DeleteModel(
            name='BeautyCenterStaff',
        ),
    ]
