# Generated by Django 4.2 on 2023-05-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_remove_beautycenterstaff_beauty_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
