# Generated by Django 4.2 on 2023-04-12 02:57

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, max_length=8, null=True)),
                ('treatment_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None)),
                ('scientific_publications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
                ('professional_memberships', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
                ('professional_awards_degree', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
                ('vocational_courses_conferences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
                ('currency_unit', models.CharField(blank=True, choices=[('dollar', '$'), ('euro', '€'), ('tl', '₺')], max_length=6, null=True)),
                ('patient_consultation', models.BooleanField(default=False)),
                ('academic_consultation', models.BooleanField(default=False)),
                ('cv', models.FileField(blank=True, default='default_cv.png', null=True, upload_to='doctors/cv_upload')),
                ('about_doctor', models.TextField(blank=True, null=True)),
                ('hobbies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None)),
                ('avatar', models.ImageField(blank=True, default='default-avatar.jpg', upload_to='doctors/avatar_upload', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'gif', 'png'])])),
                ('title', models.CharField(choices=[('professor doctor', 'Professor Doctor'), ('associate professor', 'Associate Professor'), ('specialist', 'Specialist'), ('lecturer', 'Lecturer')], max_length=30)),
                ('orcid_account', models.URLField(null=True)),
                ('pubmed_account', models.URLField(null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=100, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='authentication.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='authentication.country')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='authentication.profession')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_patient',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Health Representative', 'Health Representative')], default='Patient', max_length=155),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
