# Generated by Django 4.2 on 2023-04-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_doctorprofile_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(),
        ),
    ]
