# Generated by Django 4.2 on 2023-04-12 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_doctorprofile_user_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='doctors/id_card_upload'),
        ),
        migrations.CreateModel(
            name='PatientsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('patient_file', models.FileField(blank=True, null=True, upload_to='patient/%Y/%m/%d/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_files', to='authentication.patientprofile')),
            ],
        ),
    ]
