# Generated by Django 4.2 on 2023-04-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_doctorprofile_id_card_user_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Health Representative', 'Health Representative')], max_length=155, null=True),
        ),
    ]
