# Generated by Django 4.2 on 2023-04-13 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='academic_consultation',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='patient_consultation',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='professional_awards_degree',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='professional_memberships',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='scientific_publications',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='treatment_methods',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='vocational_courses_conferences',
        ),
    ]
