# Generated by Django 4.2 on 2023-04-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_doctorprofile_orcid_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
