# Generated by Django 4.2 on 2023-04-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_education_city_alter_experience_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='title',
            field=models.CharField(blank=True, choices=[('professor doctor', 'Professor Doctor'), ('associate professor', 'Associate Professor'), ('specialist', 'Specialist'), ('lecturer', 'Lecturer')], max_length=30, null=True),
        ),
    ]
