# Generated by Django 4.2 on 2023-04-24 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_education_end_year_alter_education_start_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
