# Generated by Django 4.2 on 2023-04-30 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('authentication', '0018_remove_profession_full_path_remove_profession_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='hospital.hospital'),
        ),
    ]
