# Generated by Django 4.2 on 2023-05-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_center', '0001_initial'),
        ('authentication', '0019_doctorprofile_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='beauty_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='beauty_center.beautycenter'),
        ),
    ]
