# Generated by Django 4.2 on 2023-05-02 17:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_doctorprofile_beauty_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='about_doctor',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
