# Generated by Django 4.2 on 2023-05-16 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_alter_doctorprofile_about_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
