# Generated by Django 4.2 on 2023-05-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_disease_doctorprofile_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='diseases',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctors', to='authentication.disease'),
        ),
    ]
