# Generated by Django 4.2 on 2023-06-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_alter_doctorprofile_diseases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='diseases',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='authentication.disease'),
        ),
    ]
