# Generated by Django 4.2 on 2023-06-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_alter_doctorprofile_diseases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unspecified', 'Unspecified')], default='unspecified', max_length=20),
        ),
    ]
