# Generated by Django 4.2 on 2023-08-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_doctorprofile_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='is_online',
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
