# Generated by Django 4.2 on 2023-09-18 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='phone',
        ),
    ]
