# Generated by Django 4.2 on 2023-09-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_remove_doctorprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting')], default='Waiting', max_length=100),
        ),
    ]
