# Generated by Django 4.2 on 2023-10-18 04:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_alter_doctorprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='authentication.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='authentication.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='patientsfile',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_files', to='authentication.patientprofile'),
        ),
        migrations.AlterField(
            model_name='usersocialmedia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_medias', to='authentication.doctorprofile'),
        ),
    ]
