# Generated by Django 4.2 on 2023-04-18 08:58

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_time', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('reserved', models.BooleanField(default=False)),
                ('available_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
