# Generated by Django 4.2 on 2023-04-19 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
