# Generated by Django 4.2 on 2023-07-20 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_appointmentrequestfile_is_downloaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='appointment.appointmentrequest')),
            ],
        ),
    ]
