# Generated by Django 4.2 on 2023-07-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_roommember_meeting_doctor_meeting_meet_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
