# Generated by Django 4.2 on 2023-07-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_meeting_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='appointment_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='appointment.appointmentrequest'),
        ),
    ]
